var annotated_dup =
[
    [ "cse335", null, [
      [ "Polygon", "classcse335_1_1_polygon.html", "classcse335_1_1_polygon" ]
    ] ],
    [ "Actor", "class_actor.html", "class_actor" ],
    [ "ActualMachineSystem", "class_actual_machine_system.html", "class_actual_machine_system" ],
    [ "AirAccepter", "class_air_accepter.html", "class_air_accepter" ],
    [ "AirSink", "class_air_sink.html", "class_air_sink" ],
    [ "AirSource", "class_air_source.html", "class_air_source" ],
    [ "AnimChannel", "class_anim_channel.html", "class_anim_channel" ],
    [ "AnimChannelAngle", "class_anim_channel_angle.html", "class_anim_channel_angle" ],
    [ "AnimChannelPoint", "class_anim_channel_point.html", "class_anim_channel_point" ],
    [ "CanadianExperienceApp", "class_canadian_experience_app.html", "class_canadian_experience_app" ],
    [ "CardReader", "class_card_reader.html", "class_card_reader" ],
    [ "Component", "class_component.html", "class_component" ],
    [ "Cylinder", "class_cylinder.html", "class_cylinder" ],
    [ "Drawable", "class_drawable.html", "class_drawable" ],
    [ "HaroldFactory", "class_harold_factory.html", "class_harold_factory" ],
    [ "HeadTop", "class_head_top.html", "class_head_top" ],
    [ "ImageDrawable", "class_image_drawable.html", "class_image_drawable" ],
    [ "Instrument", "class_instrument.html", "class_instrument" ],
    [ "Machine", "class_machine.html", "class_machine" ],
    [ "Machine1Factory", "class_machine1_factory.html", "class_machine1_factory" ],
    [ "Machine2Factory", "class_machine2_factory.html", "class_machine2_factory" ],
    [ "MachineDemoApp", "class_machine_demo_app.html", "class_machine_demo_app" ],
    [ "MachineDialog", "class_machine_dialog.html", "class_machine_dialog" ],
    [ "MachineDrawable", "class_machine_drawable.html", "class_machine_drawable" ],
    [ "MachineStandin", "class_machine_standin.html", "class_machine_standin" ],
    [ "MachineSystem", "class_machine_system.html", "class_machine_system" ],
    [ "MachineSystemFactory", "class_machine_system_factory.html", "class_machine_system_factory" ],
    [ "MachineSystemIsolator", "class_machine_system_isolator.html", "class_machine_system_isolator" ],
    [ "MainFrame", "class_main_frame.html", "class_main_frame" ],
    [ "Picture", "class_picture.html", "class_picture" ],
    [ "PictureFactory", "class_picture_factory.html", "class_picture_factory" ],
    [ "PictureObserver", "class_picture_observer.html", "class_picture_observer" ],
    [ "Pipe", "class_pipe.html", "class_pipe" ],
    [ "PolyDrawable", "class_poly_drawable.html", "class_poly_drawable" ],
    [ "RotatedBitmap", "class_rotated_bitmap.html", "class_rotated_bitmap" ],
    [ "Shape", "class_shape.html", "class_shape" ],
    [ "SpartyFactory", "class_sparty_factory.html", "class_sparty_factory" ],
    [ "StartTimeDlg", "class_start_time_dlg.html", "class_start_time_dlg" ],
    [ "StruckInstrument", "class_struck_instrument.html", "class_struck_instrument" ],
    [ "Timeline", "class_timeline.html", "class_timeline" ],
    [ "TimelineDlg", "class_timeline_dlg.html", "class_timeline_dlg" ],
    [ "Tubing", "class_tubing.html", "class_tubing" ],
    [ "ViewEdit", "class_view_edit.html", "class_view_edit" ],
    [ "ViewTimeline", "class_view_timeline.html", "class_view_timeline" ]
];